version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - node-modules
          
      - run: npm install
      - run: npm run upload

      - save_cache:
          key: node-modules
          paths:
            - ~/node_modules
